# Self-contained deploy entry-point for a Cimatron API plugin.
# Generated by /package-installer on first run — safe to re-run anytime.
#
# What it does:
#   1. Caches the package installer template under .tools\package-installer\
#      (downloads from GitHub on first run, or when -Update is passed).
#   2. Invokes build-installer.ps1 from that cache to build the redistributable
#      installer EXE in .\dist\.
#
# Re-run with -Update to refresh the cached template after this repo publishes
# a new release of the installer scaffolding.

[CmdletBinding()]
param(
    [ValidateSet('Debug', 'Release')]
    [string]$Configuration = 'Release',

    [string]$Out = './dist',

    [switch]$NoUninstall,

    [string]$TargetVersion = 'any',

    [switch]$Update
)

$ErrorActionPreference = 'Stop'

$RepoOwner  = 'CimConnor'
$RepoName   = 'Cimatron-API-Claude-Docs'
$RepoBranch = 'main'
$RepoSubpath = 'plugins/cimatron-api/skills/package-installer/installer-template'
$BaseUrl = "https://raw.githubusercontent.com/$RepoOwner/$RepoName/$RepoBranch/$RepoSubpath"

$ScriptDir = $PSScriptRoot
$CacheDir  = Join-Path $ScriptDir '.tools\package-installer'
$TemplateFiles = @('Installer.csproj', 'Program.cs', 'app.manifest', 'build-installer.ps1')

function Test-PackageInstallerCache {
    foreach ($name in $TemplateFiles) {
        if (-not (Test-Path -LiteralPath (Join-Path $CacheDir $name))) { return $false }
    }
    return $true
}

function Update-PackageInstallerCache {
    Write-Host "Fetching package installer template from $BaseUrl"
    New-Item -ItemType Directory -Force -Path $CacheDir | Out-Null
    foreach ($name in $TemplateFiles) {
        $url = "$BaseUrl/$name"
        $dest = Join-Path $CacheDir $name
        Write-Host "  $name"
        try {
            Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing
        } catch {
            throw "Could not download '$name' from $url`n$($_.Exception.Message)"
        }
    }
}

if ($Update -or -not (Test-PackageInstallerCache)) {
    Update-PackageInstallerCache
} else {
    Write-Host "Package installer cached at $CacheDir"
}

$BuildScript = Join-Path $CacheDir 'build-installer.ps1'
if (-not (Test-Path -LiteralPath $BuildScript)) {
    throw "build-installer.ps1 missing from $CacheDir even after cache refresh."
}

$buildArgs = @{
    Configuration = $Configuration
    Out           = $Out
    TargetVersion = $TargetVersion
    PluginRoot    = $ScriptDir
    TemplateDir   = $CacheDir
}
if ($NoUninstall) { $buildArgs.NoUninstall = $true }

& $BuildScript @buildArgs
exit $LASTEXITCODE
